### ISSUE TITLE
YouTube独自リアクション画像を表示したい

### ISSUE THREAD

**Issue by aka7774** [xpadev-net/niconicomments-for-onecomme#4]
お世話になっております。

推しがそろそろYouTubeメンバーシップを始められそうなので、メンバー限定の自作絵文字を画面に流したいと思っています。

わんコメのフォーラムによると、
"エモートが文字列として表示される問題については画像をそのまま表示できるよう、現在対応作業を進めていますので、少々お待ちください"
"ここのフォーラムはあまり頻繁に確認をしていないため、GitHubのIssue または Twitter まで連絡をいただけると幸いです"
とのことでしたので、Issueを立てさせていただきました。

既にご存じかと思いますが、拙作forkは、
- YouTubeが絵文字をsvg画像としてimgタグを用いて表示しようとする仕様
- ニコニコ動画が一部記号をHTMLエンティティとして表示しようとする仕様
に対して、暫定的に文字化け感の無いように誤魔化しているだけのものであり、
Unicodeで表現できないYouTube独自の絵文字は文字列として表示されてしまう状態です。
(PRしなかったのは実装内容が不完全だったからであり他意はありません)

引用元のご対応はTwitchのエモートを画像として表示するもののようですが、
TwitchのエモートもImgタグで表示する仕組みのようなので、
これが対応されれば私のやりたいことも同時に満たされると思っています。
(ついでにニコ生のHTMLエンティティ変換も必要なくなると思っています。つまりfork丸ごと不要になる)
((あらたにHTMLタグをコメントしてくる荒らし対応みたいな作業が発生しそうですが・・・))

ご対応を楽しみにしております。よろしくお願いいたします。

**Comment by xpadev-net** [comment]
わざわざありがとうございます m(_ _)m

画像の対応についてですが、コメント描画にcanvasを用いている都合上、そのまま画像を表示することが出来ません
そのため、画像を読み込み、canvasに転写するという形で実装を行っているため、htmlタグすべてをパースできるようになったというわけでは有りません

ざっと確認したところakaさんが対応してくださったニコ生のhtmlエンティティ以外ではimgタグしか流れてこなさそうだったため、imgタグをパース→akaさんのエンティティ変換という順で実装を行いました ( 3612a65aaf5f4b7f856df05bfdfecdd44e291d8d )
gifが再生されないという問題はありますが、一旦これでリリースとしたいと思います


他にもなにか問題などあれば別途問い合わせていただけると幸いです
