### ISSUE TITLE
絵文字が大きく表示され過ぎて見切れてしまう

### ISSUE THREAD

**Issue by tkykmts** [xpadev-net/niconicomments-for-onecomme#6]
## 現象
YouTube Liveのチャットを読み込んだ際、絵文字がテキストよりも大きく、枠から見切れて一部表示されない状態になります。

## キャプチャ画像

![Screenshot 2023-07-13 16-48-01](https://github.com/xpadev-net/niconicomments-for-onecomme/assets/121485666/19b9ab6d-1efd-4a5a-8cb3-143f6b0ede3e)
![Screenshot 2023-07-13 16-47-55](https://github.com/xpadev-net/niconicomments-for-onecomme/assets/121485666/07f0e789-8ac2-456f-9336-2c5110f4a299)

## 環境

Mac OS、Windowsのどちらの環境でも確認ができました。

・Mac OSの環境
- Ventura 13.4
- わんコメ 4.3.7
- OBS 29.1.1 及び Edge 114.0.1823.67で表示

・Windowsの環境
- Windows 11 22H2
- わんコメ 4.3.7
- OBS 29.1.2 及び　Edge 114.0.1823.67で表示

## その他気がついたこと
- 絵文字によってサイズが異なりました。添付画像のように半分に切れる絵文字と、1/4ほどのサイズになる絵文字があります。
- [fork版](https://github.com/aka7774/niconicomments-for-onecomme)では、同様の現象が確認できませんでした。

今回ライブ配信に使えないかと試させていただく中で気がつきました。ご参考になれば幸いです。

**Comment by aka7774** [comment]
same
https://twitter.com/currnya/status/1667935897348878336

**Comment by xpadev-net** [comment]
@aka7774 @tkykmts 

こちら対応版をリリースしましたので確認をお願いします
https://github.com/xpadev-net/niconicomments-for-onecomme/releases/tag/v0.0.3

**Comment by tkykmts** [comment]
改善を確認しました！
ご対応いただきありがとうございました！
