### ISSUE TITLE
[Feature Request] YouTubeのスパチャ表示を綺麗にしたい

### ISSUE THREAD

**Issue by aka7774** [xpadev-net/niconicomments-for-onecomme#7]
現状はタグがそのまま表示されています。
ex. &lt;div class="yt-header-sub-text"&gt;スパチャの内容&lt;/div&gt;

- 少なくともdivタグを削除したい
- できれば背景色とかも反映したいような難しいような
- 表示に正解が無いのでユーザーがカスタマイズできたほうがいいのかも

というわけで、config.jsonか何かからdecodeSpecialCharsのpairsにアクセスできるといいのかなというのと、
nico:waku:redの背景塗りつぶしバージョンみたいなものがあると嬉しいかなと思いました。
(niconicomments本体に手を入れる必要がありそう？)

わんコメの「配信サイト別追加プロパティ」から値を取ってきてcontentに設定できれば厳密ですが、
そこまで考慮するのはさすがに大げさな気もしています。(実装のイメージがついていない)
ご意見いただければ幸いです。

あと、&quot; を見かけたので、さしあたって、

const pairs: { [key: string]: string } = {
に
  "&quot;": '"',
追加と、

regex の |</?div.*?>|i を '' (空文字列)に replaceAll できるとありがたいです。
ご検討のほどをよろしくお願いいたします。

**Comment by xpadev-net** [comment]
@aka7774 要望ありがとうございます
[v0.0.4](https://github.com/xpadev-net/niconicomments-for-onecomme/releases/tag/v0.0.4)で対応したので確認をお願いします

**Comment by aka7774** [comment]
迅速なご対応に感謝いたします。
週明けまでには確認できると思いますのでお時間ください。

**Comment by aka7774** [comment]
Note:

スパチャの背景色を変える

```
  "commands": [
  {
    "condition": {
      "object": "hasGift",
      "value": true
    },
    "content": "nico:fill:green"
    }
  ],
```

金額ごとに表現を変えるには少なくともvalueに範囲指定が必要そう。
(虹スパなど、スパチャの色による遊びや格付け意識がありそう？)
どうすれば流れる文字の演出として適切かは要検討。

ex. price >= 10000 のスパチャは赤スパと呼ばれて一目置かれている。

| 金額 | 色 | 文字数 | 表示時間 |
| ---- | ---- | ---- | ---- |
| 0－199円 | 青 |   |   |
| 200－499円 | 水色 | 50 |   |
| 500－999円 | 黄緑 | 150 | 2分 |
| 1,000－1,999円 | 黄 | 200 | 5分 |
| 2,000－4,999円 | 橙 | 225 | 10分 |
| 5,000－9,999円 | マゼンタ | 250 | 30分 |
| 10,000－19,999円 | 赤 | 270 | 1時間 |
| 20,000－29,999円 | 赤 | 290 | 2時間 |
| 30,000－39,999円 | 赤 | 310 | 3時間 |
| 40,000－49,999円 | 赤 | 330 | 4時間 |
| 50,000円 | 赤 | 350 | 5時間 |

**Comment by xpadev-net** [comment]
あーたしかにrangeで表現できたほうが良さそうですね
土日はあまり時間が取れないので月曜辺りになると思いますが対応します

**Comment by aka7774** [comment]
hasGiftはスパチャがあってもfalseらしく使えませんでした。
他に==で指定できるCommentのプロパティが見当たらないのでrange対応が結局必要かも・・・。

**Comment by xpadev-net** [comment]
[v0.0.5](https://github.com/xpadev-net/niconicomments-for-onecomme/releases/tag/v0.0.5) で複数条件の指定、及び比較条件の指定に対応しました

**Comment by aka7774** [comment]
細かくて恐縮ですが、
この実装だと、以下の設定では1001円以上のスパチャにしか反応しなさそうなので、
moreEqual, lessEqual を増やしてもらったほうが使いやすいはず・・・。

```
  "condition": [//適用する条件
    { 
      "object": "price", //スパチャの額が
      "operator": "moreThan", //より多い
      "value": 1000 //1000
    },
```

**Comment by aka7774** [comment]
試しに実装してみたんですが、
https://github.com/aka7774/niconicomments-for-onecomme/releases/tag/v0.0.5.1

そもそもmoreThanでも、わんコメの「コメントテスター」では反映が確認できませんでした。
実配信の機会を見て確認しようと思いますが、うまくいかない気がします。
実際に受け取ってるオブジェクトの詳細を知る方法がわかりません・・・。

**Comment by xpadev-net** [comment]
>そもそもmoreThanでも、わんコメの「コメントテスター」では反映が確認できませんでした。

ドキュメント側のミスでした(修正済み)
データは `CommonData` 直下から読み込まれるため、価格を参照する際は `price` ではなく `data.price` でした

**Comment by aka7774** [comment]
https://github.com/aka7774/niconicomments-for-onecomme/commit/c6f10d653f92c25bf15082f32f4f80f45b762249
以上のように直したつもりなんですが、これでも反映が確認できませんでした。
v0.0.6を使用しています。

**Comment by aka7774** [comment]
少し進展しましたがまだ条件が絞れていません。
https://github.com/aka7774/niconicomments-for-onecomme/commit/c6f10d653f92c25bf15082f32f4f80f45b762249
で試したところ、

- コメントテスターで「\」を指定したものも「$」や「NT$」を指定したものも「data.unit equal \」に該当しない
- nico:fill:#f0f (カラーコード)形式での指定が反映されない(色名での指定は反映される)

という状況と思われます。

本末転倒ではありますが、

```
	"commands": [
		{
			"condition": [
				{
					"object": "data.colors.headerBackgroundColor",
					"operator": "equal",
					"value": "rgba(21,101,192,1)"
				}
			],
			"content": "nico:fill:blue"
		},
```

というような指定で、200～、500～、5000～の3つ「以外」は条件に一致することを確認しています。
(実際に返されている値がわかればすべて対応できるかも知れません。YouTubeがころころ仕様変更しなければ・・・)

**Comment by xpadev-net** [comment]
>nico:fill:#f0f (カラーコード)形式での指定が反映されない(色名での指定は反映される)

niconicomments側のバグだったため修正しました

> コメントテスターで「\」を指定したものも「$」や「NT$」を指定したものも「data.unit equal \」に該当しない

てっきり送られてくる「円」の記号が「\」([U+005C](https://0g0.org/unicode/005C/))だと思っていたのですが、どうやら「¥」([U+00A5](https://0g0.org/unicode/00A5/))だったようなのでサンプルの修正を行いました

**Comment by aka7774** [comment]
うまくいきましたー!
(コメントテスターのみ確認)
たくさんのご対応ありがとうございました!

何かあれば別Issue立てさせていただきます～
